# Exercise Numpy

### Q1- Create a NumPy array of dtype float (negative and positive numbers) with 4 dimensions and print its shape

In [9]:
import numpy as np

arr = np.array([1,2,-4.5, -0.6, 3.2, -6.3, 15.7], dtype=float, ndmin=4)
print(arr.dtype, arr.ndim, arr.shape)
print(arr)

float64 4 (1, 1, 1, 7)
[[[[ 1.   2.  -4.5 -0.6  3.2 -6.3 15.7]]]]


### Q2- Apply a filter on this array to discard negative values

In [10]:
arr_p = arr[arr > 0]
print(arr_p)

[ 1.   2.   3.2 15.7]


### Q3- Print the number of elements of the new array

In [11]:
print(arr_p.size)

4


### Q4- Convert the new array to have integer values (4 bytes)

In [12]:
arr_n = arr_p.astype('i4')
print(arr_n.dtype)

int32


### Q5- Make a copy and a view of the new array

In [13]:
# a copy
arr_c = arr_n.copy()
# a view
arr_v = arr_n.view()

print(arr_c.base, arr_v.base)

None [ 1  2  3 15]


### Q6- Reshape the new array to obtain a matrix

In [16]:
arr_m = arr_p.reshape(2,2)
print(arr_m)

[[ 1.   2. ]
 [ 3.2 15.7]]


### Q7- Define a custom ufunc that subtracts 3 from the input array

In [18]:
def subtract(arr, value):
    return arr - value

myfunc = np.frompyfunc(subtract, 2, 1)

print(myfunc(arr_m, 3))

[[-2.0 -1.0]
 [0.20000000000000018 12.7]]
